"""Backend-neutral numerical optimization and isolated backend adapters."""

from openphenomena.optimization.contracts import (
    AcceptancePolicy,
    BackendInformation,
    BackendTermination,
    ConstrainedProblem,
    ConstrainedSolverBackend,
    ConstraintResidual,
    ConstraintSpecification,
    DiagnosticCallback,
    EqualityConstraint,
    EvaluationCounts,
    HessianMode,
    IterationDiagnostic,
    MultiplierEstimate,
    OptimizationVariables,
    ScalarObjective,
    ScientificAcceptance,
    SolverResult,
    SolverSettings,
    SolverSpecification,
    SolverTolerances,
    TerminationCategory,
    ThresholdAcceptancePolicy,
)

__all__ = [
    "AcceptancePolicy",
    "BackendInformation",
    "BackendTermination",
    "ConstrainedProblem",
    "ConstrainedSolverBackend",
    "ConstraintSpecification",
    "ConstraintResidual",
    "DiagnosticCallback",
    "EqualityConstraint",
    "EvaluationCounts",
    "HessianMode",
    "IterationDiagnostic",
    "MultiplierEstimate",
    "OptimizationVariables",
    "ScalarObjective",
    "ScientificAcceptance",
    "SolverResult",
    "SolverSpecification",
    "SolverSettings",
    "SolverTolerances",
    "TerminationCategory",
    "ThresholdAcceptancePolicy",
]
